# Generated by Django 2.1.7 on 2019-09-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190828_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'ordering': ['name']},
        ),
    ]
