# Generated by Django 2.1.7 on 2019-09-02 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0002_auto_20190828_2158'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clusteruserscluster', to='location.Cluster')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clusterusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DCUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dcusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='healthusers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
