# Generated by Django 2.1.7 on 2019-08-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190828_2158'),
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expectedbreedingsite',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='expectedbreedingsite',
            name='lng',
        ),
        migrations.AddField(
            model_name='expectedbreedingsite',
            name='locality',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='expectedbreedingsites', to='location.Locality'),
            preserve_default=False,
        ),
    ]
