# Generated by Django 2.1.7 on 2019-08-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190828_2158'),
        ('citizen', '0002_auto_20190828_2201'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expectedbreedingsite',
            unique_together={('name', 'phone', 'locality')},
        ),
    ]
