# Generated by Django 2.1.7 on 2019-08-28 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190828_2158'),
        ('citizen', '0003_auto_20190828_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('a1', models.BooleanField(default=False)),
                ('a2', models.BooleanField(default=False)),
                ('a3', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expectedpatients', to='location.Locality')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='expectedpatient',
            unique_together={('name', 'phone', 'locality')},
        ),
    ]
