# Generated by Django 2.1.7 on 2019-09-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0004_auto_20190828_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectedpatient',
            name='a4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expectedpatient',
            name='a5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expectedpatient',
            name='a6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expectedpatient',
            name='a7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expectedpatient',
            name='a8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expectedpatient',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/breeding-sites'),
        ),
    ]
