# Generated by Django 2.1.7 on 2019-09-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0005_auto_20190903_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expectedpatient',
            name='image',
        ),
        migrations.AddField(
            model_name='expectedbreedingsite',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/breeding-sites'),
        ),
    ]
